---

is_debug: true
is_development: true
listen:
  type: port
  bind_ip: 0.0.0.0
  port: 10007
app:
  log_level: trace
telegram:
  token: 5132540946:AAFT3bS_PLHMuVOPAqy9H3J_haLzsFo27T8
youtube:
  api_url: https://www.googleapis.com/youtube/v3
  access_token:
imgur:
  url: https://api.imgur.com/3